version: '3'
services:
    seeddms:
        container_name: seeddms
        restart: unless-stopped
        build: .
        ports:
            - 8080:80
        depends_on:
            - mariadb
        volumes:
            - seeddms_data:/var/www/seeddms/data
            - seeddms_conf:/var/www/seeddms/conf
            - seeddms_ext:/var/www/seeddms/www/ext
    mariadb:
      container_name: mariadb
      image: lscr.io/linuxserver/mariadb
      restart: unless-stopped
      environment:
        MYSQL_ROOT_PASSWORD: sql4services
        MARIADB_DATABASE: seeddms
      volumes:
      - mariadb_data:/config
volumes:
    seeddms_data:
    seeddms_conf:
    seeddms_ext:
    mariadb_data: